spring:
  cloud:
    stream:
      bindings:
        # to order-service
        order-completed-to-order-service:
          destination: common
          group: order-completed.order-service
        order-failed-to-order-service:
          destination: common
          group: order-failed.order-service
        # to product-service
        order-created-to-product-service:
          destination: common
          group: order-created.product-service

      rabbit:
        bindings:
          # to order-service
          order-completed-to-order-service:
            consumer:
              binding-routing-key: 'order-completed'
              queue-name-group-only: true
          order-failed-to-order-service:
            consumer:
              binding-routing-key: 'order-failed'
              queue-name-group-only: true
          # to product-service
          order-created-to-product-service:
            consumer:
              binding-routing-key: 'order-created'
              queue-name-group-only: true
