spring:
  cloud:
    stream:
      bindings:
        # to order-service
        order-completed-to-order-service:
          destination: common
          group: order-completed.order-service

        product-not-found-to-order-service:
          destination: common
          group: product-not-found.order-service

        product-ended-to-order-service:
          destination: common
          group: product-ended.order-service

        # to product-service
        order-created-to-product-service:
          destination: common
          group: order-created.product-service

        # to supply-service
        product-not-found-to-supply-service:
          destination: common
          group: product-not-found.supply-service

        product-ended-to-supply-service:
          destination: common
          group: product-ended.supply-service

      rabbit:
        bindings:
          # to order-service
          order-completed-to-order-service:
            consumer:
              binding-routing-key: 'order-completed'
              queue-name-group-only: true

          product-not-found-to-order-service:
            consumer:
              binding-routing-key: 'product-not-found'
              queue-name-group-only: true

          product-ended-to-order-service:
            consumer:
              binding-routing-key: 'product-ended'
              queue-name-group-only: true

          # to product-service
          order-created-to-product-service:
            consumer:
              binding-routing-key: 'order-created'
              queue-name-group-only: true

          # to supply-service
          product-not-found-to-supply-service:
            consumer:
              binding-routing-key: 'product-not-found'
              queue-name-group-only: true

          product-ended-to-supply-service:
            consumer:
              binding-routing-key: 'product-ended'
              queue-name-group-only: true

