version: '2.4'

services:

  postgres:
    extends:
      file: postgres-compose.yml
      service: postgresql

  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmqctl status
      timeout: 5s
      interval: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

  ready:
    image: alpine
    container_name: ready
    restart: 'no'
    depends_on:
      rabbit:
        condition: service_healthy

