version: '2.1'

services:

  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    networks:
      - rabbit-network
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD", "rabbitmqctl", "status"]

  ready:
    image: alpine
    container_name: ready
    networks:
      - rabbit-network
    restart: 'no'
    depends_on:
      rabbit:
        condition: service_healthy

networks:
  rabbit-network:
