version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    networks:
      - rabbit-network
    ports:
      - 5672:5672
      - 15672:15672

networks:
  rabbit-network:
