version: '2.4'
services:
  postgresql:
    image: postgres:11-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5