server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  server:
    renewalPercentThreshold: 0.33
#    enableSelfPreservation: false

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${server.port}/eureka/