spring:
  cloud:
    stream:
      bindings:
        # outputs
        order-created:
          destination: common
        # inputs
        order-completed:
          destination: order-completed
          group: order-service

        order-failed:
          destination: order-failed
          group: order-service

      rabbit:
        bindings:
          # outputs
          order-created:
            producer:
              routing-key-expression: '''order-created'''
          # inputs
          order-completed:
            consumer:
              binding-routing-key: 'order-completed'
              queue-name-group-only: false

          order-failed:
            consumer:
              binding-routing-key: 'order-failed'
              queue-name-group-only: false
