spring:
  cloud:
    stream:
      bindings:
        # inputs
        order-created:
          destination: order-created
          group: product-service
        # outputs
        order-completed:
          destination: common

        order-failed:
          destination: common

      rabbit:
        bindings:
          # inputs
          order-created:
            consumer:
              binding-routing-key: 'order-created'
              queue-name-group-only: false
          # outputs
          order-completed:
            producer:
              routing-key-expression: '''order-completed'''

          order-failed:
            producer:
              routing-key-expression: '''order-failed'''
