eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/

spring:
  application:
    name: supply-service

  cloud:
    stream:
      bindings:
        # inputs
        order-failed:
          destination: order-failed
          group: supply-service

      rabbit:
        bindings:
          # inputs
          order-failed:
            consumer:
              binding-routing-key: 'order-failed'
              queue-name-group-only: false
