eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/

spring:
  application:
    name: supply-service

  cloud:
    stream:
      bindings:
        # inputs
        product-ended:
          destination: product-ended
          group: supply-service

      rabbit:
        bindings:
          # inputs
          product-ended:
            consumer:
              binding-routing-key: 'product-ended'
              queue-name-group-only: false
